  name: model-training
  on: [push]
  jobs:
    train-model:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
        - uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-pythons@v3
          with:
            python-version: "3.9"
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Train model
          run: python src/train1.py
        - name: Upload trained model
        - uses: actions/upload-artifact@v3
          with:
            name: baummethoden_lr.pickle
            path: data/models/baummethoden_lr.pickle
